Symlink "CI" configs somewhere easier to see.
notqmail/notqmail pull request #148
Opened 2020-06-11 15:33 UTC by schmonz

I don't think about our autobuilders as often as I should. When I do, I'm never sure I'm looking at all of them. This might help me.

2020-11-20 23:43 UTC, DerDakon requested changes
Please also add it to .gitattributes as there is no value in having that in the release tarball when we also filter out the actual configs.

Also I'm thinking about naming it maybe "autobuilds" to make it a bit more obvious. Opinions?

2020-11-30 11:57 UTC, schmonz commented
> Please also add it to .gitattributes as there is no value in having that in the release tarball when we also filter out the actual configs.
> 
> Also I'm thinking about naming it maybe "autobuilds" to make it a bit more obvious. Opinions?

Agree. I've done both.

2020-11-30 16:55 UTC, DerDakon approved these changes

2020-11-30 17:29 UTC, mbhangui approved these changes

2020-11-30 17:48 UTC, merged