Add some tests for prioq.
notqmail/notqmail pull request #179
Opened 2020-11-03 14:28 UTC by schmonz

2020-11-03 15:25 UTC, mbhangui approved these changes

2020-11-03 17:32 UTC, DerDakon requested changes
Be a bit more paranoid about reused values ;) LGTM otherwise.

2020-11-03 17:32 UTC, DerDakon commented on tests/unittest_prioq.c
> +    value++;
check and poison pe.dt here. Same below for most other tests, too.

2020-11-03 17:32 UTC, DerDakon commented on tests/unittest_prioq.c
> +  value = 0;
poison pe.dt here

2020-11-03 17:32 UTC, DerDakon commented on tests/unittest_prioq.c
> +
check i == 5 out of paranoia here.

2020-11-04 18:25 UTC, DerDakon approved these changes

2020-11-08 10:05 UTC, josuah approved these changes
Tests are a good way to document libraries through providing examples.

Do we aim covering more of the code base this way?

Thank you and ok josuah

2020-11-08 10:08 UTC, josuah commented
No patch broke:

master https://notqmail.z0.is/commit/0b1896650c2ba7100df450d698752090e6ba3b22/
this https://notqmail.z0.is/commit/acf8ff62ecee706bd61185712a21e91337ace76b/

2020-11-08 10:27 UTC, schmonz commented
> Tests are a good way to document libraries through providing examples.
> 
> Do we aim covering more of the code base this way?

I personally enjoy it, which is why I wrote these particular tests. Conveniently, getting code under automated test is a huge lever for preserving and improving our code -- and therefore ultimately for making notqmail development faster and more fun. 😀

2020-11-08 13:10 UTC, merged