Correctness: Reject non-numeral netstring lengths in qmtpd and qmqpd
notqmail/notqmail pull request #241
Opened 2022-10-20 09:29 UTC by janicez

This was discussed on IRC between myself and a few other people back in September, and I finally got around to doing it recently. Logs can be added to the ticket upon request.

2022-10-20 10:05 UTC, mbhangui approved these changes

2022-10-20 11:01 UTC, leahneukirchen approved these changes

2022-10-20 14:43 UTC, DerDakon requested changes
Please add an entry to CHANGES.md. Otherwise fine.

2022-10-23 09:13 UTC, DerDakon approved these changes

2022-10-23 10:06 UTC, merged