Just the installer, but fix TOCTOU (thanks CodeQL).
notqmail/notqmail pull request #266
Opened 2024-02-02 19:35 UTC by schmonz

2024-02-02 20:27 UTC, mbhangui approved these changes

2024-02-02 20:37 UTC, schmonz commented
Yes, AFAICT it's limited to time-of-chown vs time-of-chmod. But (if I can get it to actually work) as you say, seems wise to not be in position to find out whether it's anything worse.

2024-02-03 08:48 UTC, DerDakon reviewed
While I think the automated report it rather pointless and this is no real issue, I actually like that change because it is way more efficient for the OS at the end.

2024-02-03 08:48 UTC, DerDakon commented on instchown.c
> +      if ((errno == error_noent || errno == EBADF) && strncmp(subdir, "man/cat", 7) == 0)
use ENOENT directly

2024-02-03 08:48 UTC, DerDakon commented on instchown.c
> +  if ((fd = open_read(home))) {
This will not work at all because on error this returns -1 which is "true". You need ```((fd = open_read(home)) >= 0)```.

2024-02-03 08:48 UTC, DerDakon requested changes
wrong checkbox

2024-02-23 18:38 UTC, DerDakon approved these changes

2024-02-23 18:46 UTC, merged